import React, { useState } from 'react';
import {
  MapPin,
  Calendar,
  Clock,
  DollarSign,
  Share2,
  Download,
  Copy,
  Bookmark,
  Check,
  Sparkles,
  Users,
  AlertTriangle,
  ShieldAlert,
  Info,
} from 'lucide-react';
import { TravelGuideData } from '../types';
import { WeatherWidget, WeatherInfo } from './WeatherWidget';
import { MonthlyTempChart } from './MonthlyTempChart';
import { DestinationMap } from './DestinationMap';

interface DestinationOverviewCardProps {
  guideData: TravelGuideData;
  onDownloadPDF: () => void;
  onSaveTrip: () => void;
  isSaved: boolean;
}

export const DestinationOverviewCard: React.FC<DestinationOverviewCardProps> = ({
  guideData,
  onDownloadPDF,
  onSaveTrip,
  isSaved,
}) => {
  const [copied, setCopied] = useState(false);
  const [shared, setShared] = useState(false);
  const [liveWeather, setLiveWeather] = useState<WeatherInfo | null>(null);
  const [tempUnit, setTempUnit] = useState<'C' | 'F'>('C');
  const [showAlertPopover, setShowAlertPopover] = useState(false);

  const { overview, inputs } = guideData;
  const DynamicWeatherIcon = liveWeather?.icon;
  const displayedTemp = liveWeather
    ? tempUnit === 'F'
      ? Math.round((liveWeather.temp * 9) / 5 + 32)
      : liveWeather.temp
    : null;

  const handleCopySummary = () => {
    const summaryText = `🧳 Tourism Guide for ${overview.name}
${overview.tagline}

🗓 Duration: ${inputs.durationDays} Days (${inputs.startDate} to ${inputs.endDate})
👥 Travelers: ${inputs.travelersCount} | Budget: ${inputs.budgetLevel}
☀️ Best Time to Visit: ${overview.bestTimeToVisit}
⏱ Estimated Travel Time: ${overview.estimatedTravelTime}

Generated by Tourism Guide AI.`;

    navigator.clipboard.writeText(summaryText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleShare = async () => {
    const shareData = {
      title: `Travel Guide for ${overview.name}`,
      text: `${overview.tagline} - Custom ${inputs.durationDays}-day itinerary for ${overview.name}`,
      url: window.location.href,
    };

    if (navigator.share) {
      try {
        await navigator.share(shareData);
        setShared(true);
        setTimeout(() => setShared(false), 2000);
      } catch (e) {
        // user cancelled
      }
    } else {
      navigator.clipboard.writeText(window.location.href);
      setShared(true);
      setTimeout(() => setShared(false), 2000);
    }
  };

  return (
    <div className="bg-gradient-to-br from-slate-900 via-sky-950 to-teal-950 text-white rounded-3xl p-6 sm:p-8 shadow-2xl relative overflow-hidden border border-sky-800/50 mb-8">
      {/* Decorative Background Accents */}
      <div className="absolute -top-24 -right-24 w-96 h-96 bg-sky-500/10 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute -bottom-24 -left-24 w-96 h-96 bg-teal-500/10 rounded-full blur-3xl pointer-events-none" />

      <div className="relative z-10 flex flex-col lg:flex-row lg:items-center justify-between gap-6">
        {/* Main Title & Description */}
        <div className="space-y-3 max-w-3xl">
          <div className="flex flex-wrap items-center gap-2">
            <span className="px-3 py-1 text-xs font-extrabold uppercase tracking-wider rounded-full bg-sky-500/20 text-sky-300 border border-sky-400/30 flex items-center gap-1">
              <Sparkles className="w-3.5 h-3.5" /> AI Custom Travel Guide
            </span>
            <span className="px-3 py-1 text-xs font-semibold rounded-full bg-teal-500/20 text-teal-300 border border-teal-400/30">
              {inputs.travelStyle} Style
            </span>
          </div>

          <h1 className="text-3xl sm:text-5xl font-black tracking-tight text-white flex flex-wrap items-center gap-3">
            <MapPin className="w-8 h-8 sm:w-10 sm:h-10 text-sky-400 shrink-0" />
            <span>{overview.name}</span>
            {liveWeather && DynamicWeatherIcon && (
              <button
                onClick={() => setTempUnit((prev) => (prev === 'C' ? 'F' : 'C'))}
                title="Click to toggle °C / °F"
                className="inline-flex items-center gap-2 px-3.5 py-1.5 bg-white/15 hover:bg-white/25 backdrop-blur-md rounded-2xl text-xs sm:text-sm font-bold border border-white/20 shadow-md animate-fade-in text-white shrink-0 transition-all cursor-pointer"
              >
                <DynamicWeatherIcon className={`w-5 h-5 sm:w-6 sm:h-6 ${liveWeather.color}`} />
                <span>{displayedTemp}°{tempUnit}</span>
                <span className="text-sky-200 text-xs font-semibold hidden sm:inline">• {liveWeather.label}</span>
              </button>
            )}

            {/* Weather Alert Indicator Badge with Tooltip */}
            {liveWeather && (
              <div className="relative inline-block group/alert">
                {liveWeather.alerts && liveWeather.alerts.length > 0 ? (
                  <button
                    id="weather-alert-warning-btn"
                    onClick={() => setShowAlertPopover((prev) => !prev)}
                    className="inline-flex items-center gap-1.5 px-3.5 py-1.5 bg-amber-500/25 hover:bg-amber-500/40 text-amber-300 border border-amber-400/50 rounded-2xl text-xs sm:text-sm font-extrabold shadow-lg animate-pulse cursor-pointer transition-all shrink-0"
                  >
                    <AlertTriangle className="w-4 h-4 text-amber-400 shrink-0" />
                    <span>Weather Alert ({liveWeather.alerts.length})</span>
                  </button>
                ) : (
                  <button
                    id="weather-alert-favorable-btn"
                    onClick={() => setShowAlertPopover((prev) => !prev)}
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-emerald-500/20 hover:bg-emerald-500/30 text-emerald-300 border border-emerald-400/40 rounded-2xl text-xs sm:text-sm font-bold cursor-pointer transition-all shrink-0"
                  >
                    <ShieldAlert className="w-4 h-4 text-emerald-400 shrink-0" />
                    <span>Weather Normal</span>
                  </button>
                )}

                {/* Interactive Tooltip Popover */}
                <div
                  className={`absolute top-full left-0 sm:left-auto sm:right-0 mt-2 w-80 sm:w-96 z-50 p-4 bg-slate-900/95 backdrop-blur-xl border ${
                    liveWeather.alerts && liveWeather.alerts.length > 0
                      ? 'border-amber-500/50'
                      : 'border-emerald-500/40'
                  } rounded-2xl shadow-2xl text-white space-y-3 transition-all duration-200 ${
                    showAlertPopover ? 'block' : 'hidden group-hover/alert:block'
                  }`}
                >
                  <div className="flex items-center justify-between border-b border-white/10 pb-2">
                    <div className="flex items-center gap-2 font-black text-sm">
                      {liveWeather.alerts && liveWeather.alerts.length > 0 ? (
                        <>
                          <AlertTriangle className="w-4 h-4 text-amber-400" />
                          <span className="text-amber-300">Extreme Weather Warning</span>
                        </>
                      ) : (
                        <>
                          <ShieldAlert className="w-4 h-4 text-emerald-400" />
                          <span className="text-emerald-300">Weather Status Favorable</span>
                        </>
                      )}
                    </div>
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        setShowAlertPopover(false);
                      }}
                      className="text-xs text-slate-400 hover:text-white px-1.5 py-0.5 rounded-md hover:bg-white/10"
                    >
                      ✕
                    </button>
                  </div>

                  {liveWeather.alerts && liveWeather.alerts.length > 0 ? (
                    <div className="space-y-2.5 max-h-60 overflow-y-auto pr-1">
                      {liveWeather.alerts.map((alert, idx) => (
                        <div
                          key={idx}
                          className="p-3 bg-amber-500/10 border border-amber-500/25 rounded-xl space-y-1 text-left"
                        >
                          <div className="flex items-center justify-between text-xs font-extrabold text-amber-300">
                            <span className="flex items-center gap-1.5">
                              <AlertTriangle className="w-3.5 h-3.5 text-amber-400 shrink-0" />
                              {alert.title}
                            </span>
                            <span
                              className={`px-1.5 py-0.5 text-[9px] uppercase font-black tracking-wider rounded ${
                                alert.severity === 'high'
                                  ? 'bg-rose-500/30 text-rose-300 border border-rose-400/40'
                                  : 'bg-amber-500/30 text-amber-200 border border-amber-400/30'
                              }`}
                            >
                              {alert.severity}
                            </span>
                          </div>
                          <p className="text-[11px] text-slate-300 leading-relaxed font-normal">
                            {alert.description}
                          </p>
                        </div>
                      ))}
                    </div>
                  ) : (
                    <p className="text-xs text-slate-300 leading-relaxed font-medium text-left">
                      No severe weather advisories detected for {overview.name} during the forecast period. Conditions are safe for standard travel and outdoor tours.
                    </p>
                  )}

                  <div className="text-[10px] text-sky-300/80 font-medium pt-1 border-t border-white/10 flex items-center gap-1 text-left">
                    <Info className="w-3 h-3 text-sky-400 shrink-0" />
                    <span>Monitored in real-time via Open-Meteo weather grid.</span>
                  </div>
                </div>
              </div>
            )}
          </h1>

          <p className="text-base sm:text-lg text-sky-200 font-medium italic">
            "{overview.tagline}"
          </p>

          <p className="text-sm sm:text-base text-slate-300 leading-relaxed font-normal">
            {overview.description}
          </p>

          {/* Quick Metrics Badges */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 pt-2">
            <div className="p-3 rounded-2xl bg-white/10 backdrop-blur-md border border-white/10">
              <div className="text-sky-300 flex items-center gap-1 text-xs font-medium mb-1">
                <Calendar className="w-3.5 h-3.5" /> Best Time
              </div>
              <p className="text-xs sm:text-sm font-bold">{overview.bestTimeToVisit}</p>
            </div>

            <div className="p-3 rounded-2xl bg-white/10 backdrop-blur-md border border-white/10">
              <div className="text-sky-300 flex items-center gap-1 text-xs font-medium mb-1">
                <Clock className="w-3.5 h-3.5" /> Travel Time
              </div>
              <p className="text-xs sm:text-sm font-bold">{overview.estimatedTravelTime}</p>
            </div>

            <div className="p-3 rounded-2xl bg-white/10 backdrop-blur-md border border-white/10">
              <div className="text-sky-300 flex items-center gap-1 text-xs font-medium mb-1">
                <Users className="w-3.5 h-3.5" /> Party Size
              </div>
              <p className="text-xs sm:text-sm font-bold">{inputs.travelersCount} Person(s)</p>
            </div>

            <div className="p-3 rounded-2xl bg-white/10 backdrop-blur-md border border-white/10">
              <div className="text-sky-300 flex items-center gap-1 text-xs font-medium mb-1">
                <DollarSign className="w-3.5 h-3.5" /> Budget Tier
              </div>
              <p className="text-xs sm:text-sm font-bold">{inputs.budgetLevel} ({inputs.currency})</p>
            </div>
          </div>

          {/* Real-time Weather Forecast Component */}
          <div className="pt-2 space-y-3">
            <WeatherWidget
              destination={overview.name}
              onWeatherFetched={setLiveWeather}
              unit={tempUnit}
              onUnitChange={setTempUnit}
            />

            {/* Recharts Monthly Temperature Trends Chart */}
            <MonthlyTempChart
              destination={overview.name}
              unit={tempUnit}
            />

            {/* Google Maps Destination & Attractions Visualizer */}
            <DestinationMap
              destination={overview.name}
              attractions={guideData.attractions || []}
            />
          </div>
        </div>

        {/* Action Buttons Panel */}
        <div className="flex flex-wrap lg:flex-col gap-2.5 shrink-0 justify-start lg:justify-center">
          <button
            id="overview-download-pdf-btn"
            onClick={onDownloadPDF}
            className="flex-1 lg:flex-none flex items-center justify-center gap-2 px-4 py-2.5 bg-gradient-to-r from-sky-500 to-teal-500 hover:from-sky-400 hover:to-teal-400 text-white font-bold text-xs sm:text-sm rounded-xl shadow-md transition-all active:scale-95"
          >
            <Download className="w-4 h-4" />
            <span>Download PDF</span>
          </button>

          <button
            id="overview-save-trip-btn"
            onClick={onSaveTrip}
            className={`flex-1 lg:flex-none flex items-center justify-center gap-2 px-4 py-2.5 font-bold text-xs sm:text-sm rounded-xl border transition-all active:scale-95 ${
              isSaved
                ? 'bg-emerald-500 text-white border-emerald-400'
                : 'bg-white/10 hover:bg-white/20 text-white border-white/20'
            }`}
          >
            <Bookmark className={`w-4 h-4 ${isSaved ? 'fill-current' : ''}`} />
            <span>{isSaved ? 'Saved in Library' : 'Save Itinerary'}</span>
          </button>

          <button
            id="overview-copy-btn"
            onClick={handleCopySummary}
            className="flex-1 lg:flex-none flex items-center justify-center gap-2 px-4 py-2.5 bg-white/10 hover:bg-white/20 text-white font-bold text-xs sm:text-sm rounded-xl border border-white/20 transition-all active:scale-95"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? 'Copied!' : 'Copy Summary'}</span>
          </button>

          <button
            id="overview-share-btn"
            onClick={handleShare}
            className="flex-1 lg:flex-none flex items-center justify-center gap-2 px-4 py-2.5 bg-white/10 hover:bg-white/20 text-white font-bold text-xs sm:text-sm rounded-xl border border-white/20 transition-all active:scale-95"
          >
            {shared ? <Check className="w-4 h-4 text-emerald-400" /> : <Share2 className="w-4 h-4" />}
            <span>{shared ? 'Link Copied!' : 'Share Trip'}</span>
          </button>
        </div>
      </div>
    </div>
  );
};
